drone_position: "0.0 7.5 0.0"
drone_orientation: "0.0 0.0 0.0"
orca_orientation: "-1.57 0.0 0.0"
water_jerlow: "0.20"
docking_station_position: "0.0 7.5 4.0"
docking_station_orientation: "1.57 0.0 1.57"
pool_position: "0.0 3.0 -0.2"
pool_orientation: "-1.57 0.0 0.0"

fls_beams: "512"
fls_bins: "500"
fls_horizontal_fov: "120.0"
fls_vertical_fov: "30.0"
fls_range_min: "0.5"
fls_range_max: "25.0"
fls_gain: "1.1"
fls_noise_multiplicative: "0.01"
fls_noise_additive: "0.02"
